import Head from "next/head";
import { Inter } from "@next/font/google";
import Navbar from "@/Components/Navbar";
import Hero from "@/Components/Hero";
import CardNFT from "@/Components/CardNFT";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>SpeedRun Ethereum</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main
        id="home"
        className="bg-base-100 h-screen flex justify-center items-center w-full"
      >
        <Hero />
      </main>
      <section
        id="solutions"
        className="bg-base-100 min-h-screen flex justify-center items-center w-full divide-y-2"
      >
        <CardNFT />
      </section>
    </>
  );
}
